---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
      volumes:
      - name: mypd #we can give multiple volumes
        persistentVolumeClaim:
          claimName: mypriyanshu #pvc name 
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: "p"
            - name: MYSQL_USER
              value: priyanshu
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: "p"         
          volumeMounts:
            - name: mypd
              mountPath: /var/lib/mysql


