apiVersion: v1
kind: PersistentVolume
metadata:
  name:   mypv
spec:
  # storageClassName: ""
  # claimRef:
  #   name: foo-pvc
  #   namespace: foo
  capacity:
    storage: 1Gi
  hostPath : 
        path : /home/test  
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
  # fc:
  #   targetWWNs: ["50060e801049cfd1"]
  #   lun: 0
  #   readOnly: false   
  






   