apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 10
  selector:
    app: nginx
    region : india
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        region : india
        school : new
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

